from typing import List
import com.infinitekind.moneydance.model
import com.infinitekind.tiksync
import com.moneydance.apps.md.controller
import com.moneydance.apps.md.controller.fileimport
import com.moneydance.security
import gui
import resources


class HelperWindow:
    def __init__(self, g: gui.MainFrame, g2: gui.AccountPanel, c: com.infinitekind.moneydance.model.AccountBook): ...
    
    def close(self) -> None: ...
    
    def getAccountPanel(self) -> gui.AccountPanel: ...
    
    def getTitlePanel(self, s: str) -> 'javax.swing.JPanel': ...
    
    def grabFocus(self, j: 'javax.swing.JComponent') -> None: ...
    
    def updateText(self, j: 'javax.swing.JComponent', s: str) -> None: ...
    
    
class HomePageView:
    def __init__(self): ...
    
    def getGUIView(self, c: com.infinitekind.moneydance.model.AccountBook) -> 'javax.swing.JComponent': ...
    
    def getID(self) -> str: ...
    
    def refresh(self) -> None: ...
    
    def reset(self) -> None: ...
    
    def setActive(self, b: bool) -> None: ...
    
    def toString(self) -> str: ...
    
    
class MoneydanceUI(resources.MDResourceProvider):
    def __init__(self, c: com.moneydance.apps.md.controller.Main): ...
    
    def askForAccountBookNameToSave(self) -> 'java.io.File': ...
    
    def askForInput(self, s: str, s2: str, s3: str, b: bool) -> str: ...
    
    def askQuestion(self, s: str) -> bool: ...
    
    def dataFileOpened(self, c: com.moneydance.apps.md.controller.AccountBookWrapper) -> bool: ...
    
    def doNetSync(self) -> None: ...
    
    def getErrorMessageHTML(self, j: 'java.lang.Throwable') -> str: ...
    
    def getFileImporter(self, j: 'java.io.File') -> com.moneydance.apps.md.controller.fileimport.FileImporter: ...
    
    def getMain(self) -> com.moneydance.apps.md.controller.Main: ...
    
    def getPassphrase(self, s: str) -> str: ...
    
    def getSecretKeyCallback(self, c: com.moneydance.apps.md.controller.AccountBookWrapper) -> com.moneydance.security.SecretKeyCallback: ...
    
    def go(self) -> None: ...
    
    def importFile(self, s: str) -> None: ...
    
    def importFiles(self, list: List['java.io.File']) -> None: ...
    
    def initializePythonInterpreter(self, o: 'org.python.util.PythonInterpreter') -> None: ...
    
    def prepareToOpenData(self, c: com.moneydance.apps.md.controller.AccountBookWrapper) -> com.moneydance.apps.md.controller.AccountBookWrapper: ...
    
    def resetPythonInterpreter(self, o: 'org.python.util.PythonInterpreter') -> None: ...
    
    def selectAccount(self, c: com.infinitekind.moneydance.model.Account) -> bool: ...
    
    def setStatus(self, s: str, f: float) -> None: ...
    
    def showAbout(self) -> None: ...
    
    def showBudget(self, s: str) -> None: ...
    
    def showBudgetTool(self, s: str) -> None: ...
    
    def showCOA(self, s: str) -> None: ...
    
    def showCategories(self, s: str) -> None: ...
    
    def showErrorMessage(self, s: str) -> None: ...
    
    def showImportUI(self, s: str, c: com.infinitekind.moneydance.model.Account) -> None: ...
    
    def showInfoMessage(self, s: str) -> None: ...
    
    def showInternetURL(self, s: str) -> None: ...
    
    def showMainView(self) -> None: ...
    
    def showObject(self, c: com.infinitekind.tiksync.SyncRecord) -> None: ...
    
    def showPreferences(self) -> None: ...
    
    def showReminders(self) -> None: ...
    
    def showReport(self, c: com.infinitekind.moneydance.model.ReportSpec) -> None: ...
    
    def showReports(self) -> None: ...
    
    def showSearch(self) -> None: ...
    
    def showTxn(self, c: com.infinitekind.moneydance.model.AbstractTxn) -> None: ...
    
    def showTxnFromURI(self, s: str) -> None: ...
    
    def showUpcomingReminders(self) -> None: ...
    
    def shutdownApp(self, b: bool) -> bool: ...
    
    def shutdownCompleted(self) -> None: ...
    
    
class N12EHtml:
    BOLD_BEGIN = u'<b>'
    BOLD_END = u'</b>'
    CENTER_BEGIN = u'<center>'
    CENTER_END = u'</center>'
    HTML_BEGIN = u'<html>'
    HTML_END = u'</html>'
    LI_BEGIN = u'<li>'
    LI_END = u'</li>'
    NBSP = u'&nbsp;'
    PARA_BEGIN = u'<p>'
    PARA_END = u'</p>'
    TABLE_BEGIN = u'<table>'
    TABLE_END = u'</table>'
    TCOL_BEGIN = u'<td>'
    TCOL_END = u'</td>'
    THEAD_BEGIN = u'<th>'
    THEAD_END = u'</th>'
    TROW_BEGIN = u'<tr>'
    TROW_END = u'</tr>'
    UL_BEGIN = u'<ul>'
    UL_END = u'</ul>'
    
    def __init__(self): ...
    
    
class ViewFactory(com.moneydance.apps.md.controller.ViewListener):
    def __init__(self, c: com.moneydance.apps.md.controller.Main, g: gui.MoneydanceGUI): ...
    
    def addInternalView(self, homePageView: HomePageView) -> None: ...
    
    def getAllViews(self) -> List[HomePageView]: ...
    
    def goneAway(self) -> None: ...
    
    def viewForID(self, s: str) -> HomePageView: ...
    
    def viewListModified(self) -> None: ...
    
    
