from typing import List
import com.infinitekind.moneydance.model


class AccountEditor:
    def __init__(self): ...
    
    def applyToAccount(self, c: com.infinitekind.moneydance.model.Account) -> bool: ...
    
    def getEditorFields(self) -> List['EditorField']: ...
    
    
class EditorField:
    def __init__(self, o: object, j: 'javax.swing.JComponent'): ...
    
    def getField(self) -> 'javax.swing.JComponent': ...
    
    def getLabel(self) -> object: ...
    
    def saveEdits(self) -> None: ...
    
    
