from typing import Dict, List
import com.infinitekind.moneydance.model
import com.infinitekind.moneydance.online


class FIProfile:
    def __init__(self, s: str, s2: str, i: int): ...
    
    def getId(self) -> str: ...
    
    def getInfoDate(self) -> int: ...
    
    def getNamingAuth(self) -> str: ...
    
    def setInfoDate(self, i: int) -> None: ...
    
    
class OFXAuthInterface:
    def __init__(self): ...
    
    def authenticateUser(self, c: com.infinitekind.moneydance.model.OnlineService, s: str, c2: com.infinitekind.moneydance.model.OnlineAccountProxy) -> com.infinitekind.moneydance.online.OFXAuthInfo: ...
    
    
class OFXConnection:
    DEBUG = False
    DEBUG_MESSAGES = False
    DEFAULT_APP_ID = u'QWIN'
    DEFAULT_APP_VER = u'2900'
    NATIVE_APP_ID = u'MDNC'
    NATIVE_APP_VER = u'2019'
    
    def __init__(self, c: com.infinitekind.moneydance.model.OnlineService, c2: com.infinitekind.moneydance.online.OnlineBankingUI): ...
    
    def changePIN(self, c: com.infinitekind.moneydance.online.OFXAuthInfo, s: str) -> None: ...
    
    def createNewMail(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy, c2: com.infinitekind.moneydance.model.OnlineMail) -> None: ...
    
    def createPayee(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy, c2: com.infinitekind.moneydance.model.OnlinePayee) -> None: ...
    
    def createPayment(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy, c2: com.infinitekind.moneydance.model.OnlinePayment, c3: com.infinitekind.moneydance.model.OnlinePayee) -> com.infinitekind.moneydance.model.OnlinePayment: ...
    
    def editPayment(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy, c2: com.infinitekind.moneydance.model.OnlinePayment) -> com.infinitekind.moneydance.model.OnlinePayment: ...
    
    def getTransactions(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy) -> None: ...
    
    @staticmethod
    def main(list: List[str]) -> None: ...
    
    def modifyPayee(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy, c2: com.infinitekind.moneydance.model.OnlinePayee) -> None: ...
    
    def processDownloadedOFX(self, j: 'java.io.InputStream') -> None: ...
    
    def refreshPaymentList(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy) -> None: ...
    
    def refreshServiceInfo(self) -> None: ...
    
    def removePayee(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy, c2: com.infinitekind.moneydance.model.OnlinePayee) -> None: ...
    
    def removePayment(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy, c2: com.infinitekind.moneydance.model.OnlinePayment) -> None: ...
    
    def setDebugWriter(self, j: 'java.io.Writer') -> None: ...
    
    def setStartDateAdjustment(self, i: int) -> None: ...
    
    def syncMail(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy) -> None: ...
    
    def syncPayeeList(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy) -> None: ...
    
    def syncPaymentList(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy) -> None: ...
    
    def updateAccountList(self) -> bool: ...
    
    def updateFIProfile(self) -> None: ...
    
    
    class OFXTransaction:
        def __init__(self, oFXConnection: 'OFXConnection', oFXTag: 'OFXTag', oFXTag2: 'OFXTag'): ...
        
        def getResponse(self) -> 'OFXTag': ...
        
        def setResponse(self, oFXTag: 'OFXTag') -> None: ...
        
        
    
class OFXDateFormatter:
    FORMAT_YYYYMMDD = 4
    FORMAT_YYYYMMDDHH = 3
    FORMAT_YYYYMMDDHHMM = 2
    FORMAT_YYYYMMDDHHMMSS = 1
    FORMAT_YYYYMMDDHHMMSS_MMM = 0
    FORMAT_YYYYMMDDHHMMSS_MMM_TZ = 5
    
    def __init__(self): ...
    
    def formatDate(self, j: 'java.util.Date', i: int) -> str: ...
    
    @staticmethod
    def main(list: List[str]) -> None: ...
    
    def parseDate(self, s: str) -> 'java.util.Date': ...
    
    def parseDateInt(self, s: str, i: int) -> int: ...
    
    
class OFXInfo:
    STATUS_LEVEL_ERROR = 2
    STATUS_LEVEL_INFO = 0
    STATUS_LEVEL_WARN = 1
    TAG_TYPE_AGGREGATE = 30000
    TAG_TYPE_OFXBoolean = 30004
    TAG_TYPE_OFXDate = 30003
    TAG_TYPE_OFXDouble = 30005
    TAG_TYPE_OFXInteger = 30002
    TAG_TYPE_OFXString = 30001
    
    def __init__(self): ...
    
    @staticmethod
    def getInstance(s: str) -> 'OFXInfo': ...
    
    def getStatusMessage(self, i: int) -> str: ...
    
    def getStatusSeverity(self, i: int) -> int: ...
    
    
class OFXInfo102(OFXInfo):
    STATUS_LEVEL_ERROR = 2
    STATUS_LEVEL_INFO = 0
    STATUS_LEVEL_WARN = 1
    TAG_TYPE_AGGREGATE = 30000
    TAG_TYPE_OFXBoolean = 30004
    TAG_TYPE_OFXDate = 30003
    TAG_TYPE_OFXDouble = 30005
    TAG_TYPE_OFXInteger = 30002
    TAG_TYPE_OFXString = 30001
    
    def __init__(self): ...
    
    def getStatusMessage(self, i: int) -> str: ...
    
    def getStatusSeverity(self, i: int) -> int: ...
    
    
class OFXInfo103(OFXInfo):
    STATUS_LEVEL_ERROR = 2
    STATUS_LEVEL_INFO = 0
    STATUS_LEVEL_WARN = 1
    TAG_TYPE_AGGREGATE = 30000
    TAG_TYPE_OFXBoolean = 30004
    TAG_TYPE_OFXDate = 30003
    TAG_TYPE_OFXDouble = 30005
    TAG_TYPE_OFXInteger = 30002
    TAG_TYPE_OFXString = 30001
    
    def __init__(self): ...
    
    def getStatusMessage(self, i: int) -> str: ...
    
    def getStatusSeverity(self, i: int) -> int: ...
    
    
class OFXInfo151(OFXInfo):
    STATUS_LEVEL_ERROR = 2
    STATUS_LEVEL_INFO = 0
    STATUS_LEVEL_WARN = 1
    TAG_TYPE_AGGREGATE = 30000
    TAG_TYPE_OFXBoolean = 30004
    TAG_TYPE_OFXDate = 30003
    TAG_TYPE_OFXDouble = 30005
    TAG_TYPE_OFXInteger = 30002
    TAG_TYPE_OFXString = 30001
    
    def __init__(self): ...
    
    def getStatusMessage(self, i: int) -> str: ...
    
    def getStatusSeverity(self, i: int) -> int: ...
    
    
class OFXInfo201(OFXInfo):
    STATUS_LEVEL_ERROR = 2
    STATUS_LEVEL_INFO = 0
    STATUS_LEVEL_WARN = 1
    TAG_TYPE_AGGREGATE = 30000
    TAG_TYPE_OFXBoolean = 30004
    TAG_TYPE_OFXDate = 30003
    TAG_TYPE_OFXDouble = 30005
    TAG_TYPE_OFXInteger = 30002
    TAG_TYPE_OFXString = 30001
    
    def __init__(self): ...
    
    def getStatusMessage(self, i: int) -> str: ...
    
    def getStatusSeverity(self, i: int) -> int: ...
    
    
class OFXParser:
    def __init__(self): ...
    
    @staticmethod
    def main(list: List[str]) -> None: ...
    
    def parse(self, j: 'java.io.Reader', b: bool) -> 'OFXTag': ...
    
    def parseRemainderOfAttributes(self, j: 'java.io.PushbackReader') -> Dict[str,str]: ...
    
    
class OFXResponseHandler:
    def __init__(self): ...
    
    def getContextAccount(self) -> com.infinitekind.moneydance.model.OnlineAccountProxy: ...
    
    def handleResponseTag(self, oFXTag: 'OFXTag') -> bool: ...
    
    def setContext(self, c: com.infinitekind.moneydance.model.OnlineAccountProxy, c2: com.infinitekind.moneydance.model.OnlineService, c3: com.infinitekind.moneydance.online.OFXAuthInfo) -> None: ...
    
    
class OFXTag:
    def __init__(self): ...
    
    def addSubTag(self, oFXTag: 'OFXTag') -> 'OFXTag': ...
    
    def getAmountSubTag(self, s: str, i: int, c: com.infinitekind.moneydance.model.CurrencyType) -> int: ...
    
    def getBoolSubTag(self, s: str, b: bool) -> bool: ...
    
    def getBoolValue(self) -> bool: ...
    
    def getDateSubTag(self, s: str, oFXDateFormatter: OFXDateFormatter, i: int) -> int: ...
    
    def getDateValue(self, oFXDateFormatter: OFXDateFormatter, i: int) -> int: ...
    
    def getIntSubTag(self, s: str, i: int) -> int: ...
    
    def getIntValue(self) -> int: ...
    
    def getLongSubTag(self, s: str, i: int) -> int: ...
    
    def getLongValue(self) -> int: ...
    
    def getName(self) -> str: ...
    
    def getStrListSubTag(self, s: str) -> List[str]: ...
    
    def getStrSubTag(self, s: str, s2: str) -> str: ...
    
    def getStrValue(self) -> str: ...
    
    def getSubTag(self, i: int) -> 'OFXTag': ...
    
    def getSubTagCount(self) -> int: ...
    
    def getUrlSubTag(self, s: str, j: 'java.net.URL') -> 'java.net.URL': ...
    
    def getUrlValue(self) -> 'java.net.URL': ...
    
    def getValue(self) -> object: ...
    
    def hasName(self, s: str) -> bool: ...
    
    def hasSubTag(self, s: str) -> bool: ...
    
    def setSuppressNewLine(self, b: bool) -> None: ...
    
    def setValue(self, o: object) -> None: ...
    
    def toNewLineString(self) -> str: ...
    
    def toString(self) -> str: ...
    
    def write(self, j: 'java.io.Writer', b: bool, s: str) -> None: ...
    
    def writeWithNewLines(self, j: 'java.io.Writer') -> None: ...
    
    def writeXMLWithNewLines(self, j: 'java.io.Writer') -> None: ...
    
    
class OFXUtil:
    def __init__(self): ...
    
    @staticmethod
    def decodeString(s: str) -> str: ...
    
    @staticmethod
    def encodeString(s: str) -> str: ...
    
    @staticmethod
    def main(list: List[str]) -> None: ...
    
    
class OFXValue:
    def __init__(self): ...
    
    @staticmethod
    def formatBoolean(b: bool) -> str: ...
    
    @staticmethod
    def formatDateYYYYMMDD(j: 'java.util.Date') -> str: ...
    
    @staticmethod
    def formatDateYYYYMMDDHH(j: 'java.util.Date') -> str: ...
    
    @staticmethod
    def formatDateYYYYMMDDHHMM(j: 'java.util.Date') -> str: ...
    
    @staticmethod
    def formatDateYYYYMMDDHHMMSS(j: 'java.util.Date') -> str: ...
    
    @staticmethod
    def formatDateYYYYMMDDHHMMSS_MMM(j: 'java.util.Date') -> str: ...
    
    @staticmethod
    def formatDateYYYYMMDDHHMMSS_MMM_TZ(j: 'java.util.Date') -> str: ...
    
    @staticmethod
    def parseBoolean(s: str) -> bool: ...
    
    @staticmethod
    def parseOFXDate(s: str) -> 'java.util.Date': ...
    
    
